// <auto-generated />
using CarvedRockFitness.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarvedRockFitness.API.Migrations
{
    [DbContext(typeof(CarvedRockFitnessDbContext))]
    partial class CarvedRockFitnessDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarvedRockFitness.API.Entities.Routine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Routines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A relaxing morning yoga routine",
                            Name = "Morning Yoga",
                            UserId = 4
                        },
                        new
                        {
                            Id = 2,
                            Description = "High-intensity cardio workout",
                            Name = "Cardio Blast",
                            UserId = 5
                        },
                        new
                        {
                            Id = 3,
                            Description = "Full-body strength training",
                            Name = "Strength Training",
                            UserId = 6
                        },
                        new
                        {
                            Id = 4,
                            Description = "High-Intensity Interval Training",
                            Name = "HIIT Workout",
                            UserId = 7
                        },
                        new
                        {
                            Id = 5,
                            Description = "Core strengthening Pilates routine",
                            Name = "Pilates",
                            UserId = 8
                        },
                        new
                        {
                            Id = 6,
                            Description = "Gentle evening stretching routine",
                            Name = "Evening Stretch",
                            UserId = 9
                        },
                        new
                        {
                            Id = 7,
                            Description = "Upper body strength training",
                            Name = "Upper Body Strength",
                            UserId = 10
                        },
                        new
                        {
                            Id = 8,
                            Description = "Lower body strength training",
                            Name = "Lower Body Strength",
                            UserId = 4
                        },
                        new
                        {
                            Id = 9,
                            Description = "Comprehensive full-body workout",
                            Name = "Full Body Workout",
                            UserId = 5
                        },
                        new
                        {
                            Id = 10,
                            Description = "Intense core workout",
                            Name = "Core Workout",
                            UserId = 6
                        },
                        new
                        {
                            Id = 11,
                            Description = "Flexibility and mobility exercises",
                            Name = "Flexibility Training",
                            UserId = 7
                        },
                        new
                        {
                            Id = 12,
                            Description = "Balance and stability exercises",
                            Name = "Balance Training",
                            UserId = 8
                        },
                        new
                        {
                            Id = 13,
                            Description = "Endurance and stamina building",
                            Name = "Endurance Training",
                            UserId = 9
                        },
                        new
                        {
                            Id = 14,
                            Description = "Speed and agility drills",
                            Name = "Speed Training",
                            UserId = 10
                        },
                        new
                        {
                            Id = 15,
                            Description = "Power and explosiveness training",
                            Name = "Power Training",
                            UserId = 4
                        },
                        new
                        {
                            Id = 16,
                            Description = "Active recovery exercises",
                            Name = "Recovery Workout",
                            UserId = 5
                        },
                        new
                        {
                            Id = 17,
                            Description = "Circuit-based workout routine",
                            Name = "Circuit Training",
                            UserId = 6
                        },
                        new
                        {
                            Id = 18,
                            Description = "Bodyweight exercises",
                            Name = "Bodyweight Workout",
                            UserId = 7
                        },
                        new
                        {
                            Id = 19,
                            Description = "Kettlebell exercises",
                            Name = "Kettlebell Workout",
                            UserId = 8
                        },
                        new
                        {
                            Id = 20,
                            Description = "Dumbbell exercises",
                            Name = "Dumbbell Workout",
                            UserId = 9
                        },
                        new
                        {
                            Id = 21,
                            Description = "Barbell exercises",
                            Name = "Barbell Workout",
                            UserId = 10
                        },
                        new
                        {
                            Id = 22,
                            Description = "Resistance band exercises",
                            Name = "Resistance Band Workout",
                            UserId = 4
                        },
                        new
                        {
                            Id = 23,
                            Description = "TRX suspension training",
                            Name = "TRX Workout",
                            UserId = 5
                        },
                        new
                        {
                            Id = 24,
                            Description = "Plyometric exercises",
                            Name = "Plyometrics",
                            UserId = 6
                        },
                        new
                        {
                            Id = 25,
                            Description = "Boxing and kickboxing drills",
                            Name = "Boxing Workout",
                            UserId = 7
                        },
                        new
                        {
                            Id = 26,
                            Description = "Martial arts techniques",
                            Name = "Martial Arts Training",
                            UserId = 8
                        },
                        new
                        {
                            Id = 27,
                            Description = "Dance-based fitness routine",
                            Name = "Dance Workout",
                            UserId = 9
                        },
                        new
                        {
                            Id = 28,
                            Description = "Swimming drills and exercises",
                            Name = "Swimming Workout",
                            UserId = 10
                        },
                        new
                        {
                            Id = 29,
                            Description = "Cycling drills and exercises",
                            Name = "Cycling Workout",
                            UserId = 4
                        },
                        new
                        {
                            Id = 30,
                            Description = "Rowing drills and exercises",
                            Name = "Rowing Workout",
                            UserId = 5
                        });
                });

            modelBuilder.Entity("CarvedRockFitness.API.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TrainerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainerId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "john.doe@carvedrockfitness.com",
                            Name = "John Doe",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "jane.smith@carvedrockfitness.com",
                            Name = "Jane Smith",
                            Role = "Trainer"
                        },
                        new
                        {
                            Id = 3,
                            Email = "mike.johnson@carvedrockfitness.com",
                            Name = "Mike Johnson",
                            Role = "Trainer"
                        },
                        new
                        {
                            Id = 4,
                            Email = "emily.davis@carvedrockfitness.com",
                            Name = "Emily Davis",
                            Role = "Trainee",
                            TrainerId = 2
                        },
                        new
                        {
                            Id = 5,
                            Email = "chris.brown@carvedrockfitness.com",
                            Name = "Chris Brown",
                            Role = "Trainee",
                            TrainerId = 2
                        },
                        new
                        {
                            Id = 6,
                            Email = "patricia.taylor@carvedrockfitness.com",
                            Name = "Patricia Taylor",
                            Role = "Trainee",
                            TrainerId = 3
                        },
                        new
                        {
                            Id = 7,
                            Email = "robert.wilson@carvedrockfitness.com",
                            Name = "Robert Wilson",
                            Role = "Trainee",
                            TrainerId = 3
                        },
                        new
                        {
                            Id = 8,
                            Email = "linda.martinez@carvedrockfitness.com",
                            Name = "Linda Martinez",
                            Role = "Trainee",
                            TrainerId = 3
                        },
                        new
                        {
                            Id = 9,
                            Email = "david.anderson@carvedrockfitness.com",
                            Name = "David Anderson",
                            Role = "Trainee",
                            TrainerId = 2
                        },
                        new
                        {
                            Id = 10,
                            Email = "sarah.thomas@carvedrockfitness.com",
                            Name = "Sarah Thomas",
                            Role = "Trainee",
                            TrainerId = 2
                        });
                });

            modelBuilder.Entity("CarvedRockFitness.API.Entities.Routine", b =>
                {
                    b.HasOne("CarvedRockFitness.API.Entities.User", "User")
                        .WithMany("Routines")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarvedRockFitness.API.Entities.User", b =>
                {
                    b.HasOne("CarvedRockFitness.API.Entities.User", "Trainer")
                        .WithMany("Trainees")
                        .HasForeignKey("TrainerId");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("CarvedRockFitness.API.Entities.User", b =>
                {
                    b.Navigation("Routines");

                    b.Navigation("Trainees");
                });
#pragma warning restore 612, 618
        }
    }
}
